# Challenge 2: House Prices - Advanced Regression Techniques

## Huấn luyện mô hình cơ bản (Baseline Model Training)

Các mô hình được huấn luyện trên tập dữ liệu gốc (chưa qua feature engineering), nhằm đánh giá hiệu năng cơ bản ban đầu.

### Khai báo thư viện

In [26]:
import pandas as pd
import numpy as np
import random
import os, sys
from IPython import display


from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

### Tham số thực nghiệm

In [11]:
params = {}

params["exps_dir"] = "../exps"
params["exp_name"] = "challenge2_houseprice_standard"

params["exps_root"] = f'{params["exps_dir"]}/result1_standard'
params["save_dir"] = f'{params["exps_dir"]}/result1_{params["exp_name"]}'

params["data_path"] = f'{params["exps_dir"]}/data/train.xlsx'
params["test_path"] = f'{params["exps_dir"]}/data/test.xlsx'

params["k_fold"] = 10
params["random_state"] = 42

random.seed(params["random_state"])
os.environ['PYTHONHASHSEED'] = str(params["random_state"])
np.random.seed(params["random_state"])

### Nạp dữ liệu

In [12]:
df_train = pd.read_excel(f"{params["data_path"]}")
df_test = pd.read_excel(f"{params["test_path"]}")

In [13]:
df_train.head()

,LotShape,LandContour,LotConfig,Neighborhood,HouseStyle,OverallQual,YearRemodAdd,RoofStyle,Exterior1st,MasVnrArea,...,GrLivArea,FullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,SalePrice
0,0.750731,0.314667,0.604670,-1.206215,1.026689,0.651479,0.878668,-0.491516,0.743092,0.514104,...,0.370333,0.789741,-0.409369,-0.951226,-0.075117,-0.768736,1.005970,0.103495,0.311725,208500
1,0.750731,0.314667,-0.628316,1.954302,-0.543457,-0.071836,-0.429577,-0.491516,-0.508251,-0.570750,...,-0.482512,0.789741,0.795629,0.600495,1.638498,-0.768736,-0.094619,0.103495,0.311725,181500
2,-1.378933,0.314667,0.604670,-1.206215,1.026689,0.651479,0.830215,-0.491516,0.743092,0.325915,...,0.515013,0.789741,-0.409369,0.600495,1.638498,-0.768736,0.924445,0.103495,0.311725,223500
3,-1.378933,0.314667,-1.861302,-1.039872,1.026689,0.651479,-0.720298,-0.491516,1.055928,-0.570750,...,0.383659,-1.026041,-0.409369,0.600495,-0.931925,1.301075,0.802157,0.942959,1.650307,140000
4,-1.378933,0.314667,-0.628316,0.457215,1.026689,1.374795,0.733308,-0.491516,0.743092,1.366489,...,1.299326,0.789741,-0.409369,0.600495,1.638498,-0.768736,0.883682,0.103495,1.650307,250000

In [14]:
df_test.head()

,LotShape,LandContour,LotConfig,Neighborhood,HouseStyle,OverallQual,YearRemodAdd,RoofStyle,Exterior1st,MasVnrArea,...,CentralAir,GrLivArea,FullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars
0,0.750731,0.314667,0.604670,-0.041814,-0.543457,-0.795151,-1.156380,-0.491516,0.743092,-0.570750,...,1,-1.179256,-1.026041,0.795629,-0.951226,-0.075117,-0.768736,-0.706058,0.942959,-1.026858
1,-1.378933,0.314667,-1.861302,-0.041814,-0.543457,-0.071836,-1.301740,1.904521,1.055928,0.027027,...,1,-0.354966,-1.026041,-0.409369,-0.951226,-0.075117,-0.768736,-0.828346,0.942959,-1.026858
2,-1.378933,0.314667,0.604670,-0.707186,1.026689,-0.795151,0.636400,-0.491516,0.743092,-0.570750,...,1,0.216136,0.789741,0.795629,0.600495,1.638498,-0.768736,0.761394,-1.575431,0.311725
3,-1.378933,0.314667,0.604670,-0.707186,1.026689,-0.071836,0.636400,-0.491516,0.743092,-0.460051,...,1,0.168544,0.789741,-0.409369,0.600495,-0.931925,-0.768736,0.802157,-1.575431,0.311725
4,-1.378933,-2.512494,0.604670,1.621616,-0.543457,1.374795,0.345679,-0.491516,-1.133923,-0.570750,...,1,-0.448246,0.789741,-0.409369,-0.951226,-0.075117,-0.768736,0.557582,0.103495,0.311725

In [15]:
# Tách X, y
y = df_train["SalePrice"]
X = df_train.drop(columns=["SalePrice"])


print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
)

print("Train X:", X_train.shape)
print("Valid X:", X_valid.shape)
print("Train y:", y_train.shape)
print("Valid y:", y_valid.shape)

X shape: (1460, 27)
y shape: (1460,)
Train X: (1168, 27)
Valid X: (292, 27)
Train y: (1168,)
Valid y: (292,)

In [16]:
kfold = KFold(n_splits=params["k_fold"], shuffle=True, random_state=params["random_state"])
print(f"+ X_train: {len(X_train)}")
for fold, (train_idx, valid_idx) in enumerate(kfold.split(X_train, y_train)):
    print(f'Fold {fold}: ')
    print(f'+ train_idx: {train_idx}')
    print(f'+ valid_idx: {valid_idx}')
    print(f'+ train / valid: {valid_idx}')
    pass

+ X_train: 1168
Fold 0:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [  23   44   49   51   54   58   70   86  101  107  109  113  128  140
  155  156  158  163  174  192  198  199  209  210  218  231  233  244
  292  296  298  308  319  323  327  328  336  344  352  354  355  362
  376  377  394  405  422  424  425  428  429  435  451  462  467  477
  532  545  548  558  560  561  570  590  596  618  629  643  667  692
  694  695  706  714  731  759  762  807  808  811  816  826  837  849
  884  889  900  905  924  925  926  937  939  946  948  966  967  969
  988 1003 1013 1014 1029 1030 1039 1046 1085 1093 1101 1116 1131 1132
 1137 1154 1159 1160 1161]
+ train / valid: [  23   44   49   51   54   58   70   86  101  107  109  113  128  140
  155  156  158  163  174  192  198  199  209  210  218  231  233  244
  292  296  298  308  319  323  327  328  336  344  352  354  355  362
  376  377  394  405  422  424  425  428  429  435  451  462  467  477
  532  545  548  558  560  561  570  590  596  618  629  643  667  692
  694  695  706  714  731  759  762  807  808  811  816  826  837  849
  884  889  900  905  924  925  926  937  939  946  948  966  967  969
  988 1003 1013 1014 1029 1030 1039 1046 1085 1093 1101 1116 1131 1132
 1137 1154 1159 1160 1161]
Fold 1:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [  10   31   43   56   59   63   76   83   88   96  135  138  139  141
  168  170  208  220  240  243  247  260  265  270  274  275  290  294
  299  306  309  321  358  361  371  380  390  398  409  411  420  423
  432  442  457  465  478  486  493  497  506  513  519  533  535  538
  539  543  554  572  585  589  594  599  605  614  630  636  666  689
  712  721  723  728  732  733  752  753  767  774  780  787  796  803
  810  820  827  830  833  845  852  865  868  875  879  887  912  916
  917  918  920  940  965  978  990  991  997 1000 1004 1006 1009 1041
 1102 1111 1119 1133 1145]
+ train / valid: [  10   31   43   56   59   63   76   83   88   96  135  138  139  141
  168  170  208  220  240  243  247  260  265  270  274  275  290  294
  299  306  309  321  358  361  371  380  390  398  409  411  420  423
  432  442  457  465  478  486  493  497  506  513  519  533  535  538
  539  543  554  572  585  589  594  599  605  614  630  636  666  689
  712  721  723  728  732  733  752  753  767  774  780  787  796  803
  810  820  827  830  833  845  852  865  868  875  879  887  912  916
  917  918  920  940  965  978  990  991  997 1000 1004 1006 1009 1041
 1102 1111 1119 1133 1145]
Fold 2:
+ train_idx: [   0    1    4 ... 1164 1165 1166]
+ valid_idx: [   2    3    6   12   25   27   30   39   47   55   66   67   72   78
  100  106  120  136  178  184  211  213  215  227  237  242  256  273
  277  286  289  291  316  318  331  332  333  342  367  381  382  410
  413  427  433  448  453  458  464  471  479  481  485  523  527  536
  541  549  553  566  573  578  591  597  602  617  620  628  634  644
  660  665  670  701  711  713  715  716  722  724  743  745  771  773
  783  793  798  802  812  813  824  841  872  888  899  902  907  908
  923  947  956  973  979  980  989 1036 1045 1074 1083 1089 1098 1105
 1106 1113 1153 1155 1167]
+ train / valid: [   2    3    6   12   25   27   30   39   47   55   66   67   72   78
  100  106  120  136  178  184  211  213  215  227  237  242  256  273
  277  286  289  291  316  318  331  332  333  342  367  381  382  410
  413  427  433  448  453  458  464  471  479  481  485  523  527  536
  541  549  553  566  573  578  591  597  602  617  620  628  634  644
  660  665  670  701  711  713  715  716  722  724  743  745  771  773
  783  793  798  802  812  813  824  841  872  888  899  902  907  908
  923  947  956  973  979  980  989 1036 1045 1074 1083 1089 1098 1105
 1106 1113 1153 1155 1167]
Fold 3:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [   5   29   33   60   65   71   77   82   84   92   94  110  137  165
  182  204  221  235  248  249  254  259  261  280  305  307  310  312
  334  339  346  350  351  359  363  365  388  404  430  436  439  445
  447  461  490  494  514  522  526  528  529  534  542  552  567  575
  581  582  588  593  613  615  622  649  652  654  661  673  676  677
  678  682  690  693  704  727  730  736  737  756  764  768  772  785
  788  814  817  825  834  862  864  867  881  885  886  901  909  963
  971  985  994  998 1019 1022 1023 1053 1054 1060 1065 1069 1081 1087
 1090 1107 1108 1129 1140]
+ train / valid: [   5   29   33   60   65   71   77   82   84   92   94  110  137  165
  182  204  221  235  248  249  254  259  261  280  305  307  310  312
  334  339  346  350  351  359  363  365  388  404  430  436  439  445
  447  461  490  494  514  522  526  528  529  534  542  552  567  575
  581  582  588  593  613  615  622  649  652  654  661  673  676  677
  678  682  690  693  704  727  730  736  737  756  764  768  772  785
  788  814  817  825  834  862  864  867  881  885  886  901  909  963
  971  985  994  998 1019 1022 1023 1053 1054 1060 1065 1069 1081 1087
 1090 1107 1108 1129 1140]
Fold 4:
+ train_idx: [   1    2    3 ... 1164 1166 1167]
+ valid_idx: [   0    7    9   62   69   79   81   90   97  104  118  125  131  133
  144  145  148  172  177  181  196  212  223  228  238  239  250  251
  258  266  281  285  300  302  311  314  326  329  347  357  360  370
  373  386  389  408  440  449  450  460  475  482  499  501  504  507
  525  530  531  551  557  583  584  598  621  626  631  657  668  688
  707  717  738  746  755  757  765  777  782  789  790  801  823  829
  832  846  847  859  869  873  882  894  910  938  949  964  968  982
  999 1007 1034 1037 1043 1050 1062 1072 1078 1086 1088 1103 1110 1122
 1125 1127 1162 1163 1165]
+ train / valid: [   0    7    9   62   69   79   81   90   97  104  118  125  131  133
  144  145  148  172  177  181  196  212  223  228  238  239  250  251
  258  266  281  285  300  302  311  314  326  329  347  357  360  370
  373  386  389  408  440  449  450  460  475  482  499  501  504  507
  525  530  531  551  557  583  584  598  621  626  631  657  668  688
  707  717  738  746  755  757  765  777  782  789  790  801  823  829
  832  846  847  859  869  873  882  894  910  938  949  964  968  982
  999 1007 1034 1037 1043 1050 1062 1072 1078 1086 1088 1103 1110 1122
 1125 1127 1162 1163 1165]
Fold 5:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [  11   15   18   24   28   41   42   61   73   74   89  108  114  132
  164  167  169  173  176  179  185  193  214  222  234  257  264  267
  272  278  324  335  338  366  368  375  383  393  395  396  412  416
  417  426  444  454  456  468  483  491  495  498  500  516  518  544
  547  555  568  576  587  595  601  604  607  616  650  674  675  679
  700  708  718  720  739  741  754  781  786  799  806  818  838  839
  842  843  855  857  866  874  892  893  898  914  915  930  932  942
  944  950  976  992 1001 1005 1024 1026 1027 1032 1091 1092 1114 1117
 1124 1134 1144 1158 1164]
+ train / valid: [  11   15   18   24   28   41   42   61   73   74   89  108  114  132
  164  167  169  173  176  179  185  193  214  222  234  257  264  267
  272  278  324  335  338  366  368  375  383  393  395  396  412  416
  417  426  444  454  456  468  483  491  495  498  500  516  518  544
  547  555  568  576  587  595  601  604  607  616  650  674  675  679
  700  708  718  720  739  741  754  781  786  799  806  818  838  839
  842  843  855  857  866  874  892  893  898  914  915  930  932  942
  944  950  976  992 1001 1005 1024 1026 1027 1032 1091 1092 1114 1117
 1124 1134 1144 1158 1164]
Fold 6:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [   4   19   22   35   38   46   50   57   68   75   85   93   99  102
  105  116  117  124  126  142  149  153  154  175  188  195  203  217
  236  245  263  268  271  284  287  304  313  320  340  341  349  353
  356  369  399  407  431  434  443  446  470  473  487  489  505  512
  521  537  559  574  580  603  611  619  625  633  635  638  653  655
  656  662  664  684  691  696  697  703  726  740  750  758  760  761
  784  809  822  848  850  853  858  861  876  911  913  921  922  941
  943  958 1002 1008 1010 1035 1040 1042 1047 1055 1057 1063 1068 1120
 1121 1128 1143 1146 1152]
+ train / valid: [   4   19   22   35   38   46   50   57   68   75   85   93   99  102
  105  116  117  124  126  142  149  153  154  175  188  195  203  217
  236  245  263  268  271  284  287  304  313  320  340  341  349  353
  356  369  399  407  431  434  443  446  470  473  487  489  505  512
  521  537  559  574  580  603  611  619  625  633  635  638  653  655
  656  662  664  684  691  696  697  703  726  740  750  758  760  761
  784  809  822  848  850  853  858  861  876  911  913  921  922  941
  943  958 1002 1008 1010 1035 1040 1042 1047 1055 1057 1063 1068 1120
 1121 1128 1143 1146 1152]
Fold 7:
+ train_idx: [   0    1    2 ... 1164 1165 1167]
+ valid_idx: [   8   16   17   26   32   36   37   45   48   53  103  111  115  119
  127  151  152  157  159  160  162  171  180  190  191  194  207  225
  226  229  232  255  282  283  301  322  364  372  374  403  419  421
  437  452  469  476  480  496  503  509  511  515  517  546  569  579
  586  606  624  651  658  669  672  680  685  687  705  734  744  749
  792  797  800  821  828  844  851  877  890  895  903  904  919  927
  933  934  936  953  959  961  977  983  987  993 1015 1018 1033 1052
 1058 1067 1073 1079 1084 1096 1097 1100 1115 1118 1135 1136 1141 1147
 1148 1149 1150 1156 1166]
+ train / valid: [   8   16   17   26   32   36   37   45   48   53  103  111  115  119
  127  151  152  157  159  160  162  171  180  190  191  194  207  225
  226  229  232  255  282  283  301  322  364  372  374  403  419  421
  437  452  469  476  480  496  503  509  511  515  517  546  569  579
  586  606  624  651  658  669  672  680  685  687  705  734  744  749
  792  797  800  821  828  844  851  877  890  895  903  904  919  927
  933  934  936  953  959  961  977  983  987  993 1015 1018 1033 1052
 1058 1067 1073 1079 1084 1096 1097 1100 1115 1118 1135 1136 1141 1147
 1148 1149 1150 1156 1166]
Fold 8:
+ train_idx: [   0    2    3 ... 1165 1166 1167]
+ valid_idx: [   1   52   80   95  112  122  123  129  143  146  147  150  183  186
  197  202  219  224  246  253  262  279  293  297  303  317  325  345
  348  384  400  402  414  415  438  441  463  472  484  488  524  540
  550  556  563  571  577  608  609  610  623  627  632  637  639  640
  641  645  648  659  663  671  681  698  709  710  735  742  748  751
  770  778  795  819  835  836  854  863  880  883  896  906  928  931
  935  945  951  952  954  962  970  972  974  981  984  986  996 1011
 1012 1020 1031 1048 1049 1059 1061 1066 1075 1077 1080 1094 1099 1109
 1112 1139 1142 1157]
+ train / valid: [   1   52   80   95  112  122  123  129  143  146  147  150  183  186
  197  202  219  224  246  253  262  279  293  297  303  317  325  345
  348  384  400  402  414  415  438  441  463  472  484  488  524  540
  550  556  563  571  577  608  609  610  623  627  632  637  639  640
  641  645  648  659  663  671  681  698  709  710  735  742  748  751
  770  778  795  819  835  836  854  863  880  883  896  906  928  931
  935  945  951  952  954  962  970  972  974  981  984  986  996 1011
 1012 1020 1031 1048 1049 1059 1061 1066 1075 1077 1080 1094 1099 1109
 1112 1139 1142 1157]
Fold 9:
+ train_idx: [   0    1    2 ... 1165 1166 1167]
+ valid_idx: [  13   14   20   21   34   40   64   87   91   98  121  130  134  161
  166  187  189  200  201  205  206  216  230  241  252  269  276  288
  295  315  330  337  343  378  379  385  387  391  392  397  401  406
  418  455  459  466  474  492  502  508  510  520  562  564  565  592
  600  612  642  646  647  683  686  699  702  719  725  729  747  763
  766  769  775  776  779  791  794  804  805  815  831  840  856  860
  870  871  878  891  897  929  955  957  960  975  995 1016 1017 1021
 1025 1028 1038 1044 1051 1056 1064 1070 1071 1076 1082 1095 1104 1123
 1126 1130 1138 1151]
+ train / valid: [  13   14   20   21   34   40   64   87   91   98  121  130  134  161
  166  187  189  200  201  205  206  216  230  241  252  269  276  288
  295  315  330  337  343  378  379  385  387  391  392  397  401  406
  418  455  459  466  474  492  502  508  510  520  562  564  565  592
  600  612  642  646  647  683  686  699  702  719  725  729  747  763
  766  769  775  776  779  791  794  804  805  815  831  840  856  860
  870  871  878  891  897  929  955  957  960  975  995 1016 1017 1021
 1025 1028 1038 1044 1051 1056 1064 1070 1071 1076 1082 1095 1104 1123
 1126 1130 1138 1151]

### Lựa chọn mô hình mặc định

In [21]:
models = {
    ('Extra Trees', ExtraTreesRegressor(random_state=params["random_state"])),
    ('Random Forest', RandomForestRegressor(random_state=params["random_state"])),
    ('LightGBM', LGBMRegressor(
            random_state=params["random_state"],
            verbose=-1,
            verbosity=-1
    )),
    ('Gradient Boosting', GradientBoostingRegressor(random_state=params["random_state"])),
    ('XGBoost', XGBRegressor(random_state=params["random_state"]))
}

### Huấn luyện và đánh giá từng mô hình

In [29]:

results = []
baseline_results = {}

for name, model in models:
    baseline_results[name] = {"mae": [], "rmse": [], "r2": []}

    print(f'Model {name}:')
    kfold = KFold(n_splits=params["k_fold"], shuffle=True, random_state=params["random_state"])

    for fold, (train_idx, valid_idx) in enumerate(kfold.split(X_train, y_train)):
        X1_train, y1_train = X_train.iloc[train_idx], y_train.iloc[train_idx]
        X1_valid, y1_valid = X_train.iloc[valid_idx], y_train.iloc[valid_idx]

        model.fit(X1_train, y1_train)
        y_pred_valid = model.predict(X1_valid)

        mae = mean_absolute_error(y1_valid, y_pred_valid)
        rmse = np.sqrt(mean_squared_error(y1_valid, y_pred_valid))
        r2 = r2_score(y1_valid, y_pred_valid)

        baseline_results[name]["mae"].append(mae)
        baseline_results[name]["rmse"].append(rmse)
        baseline_results[name]["r2"].append(r2)

    print(f'+ params = {model.get_params()}')
    print(f'+ rmse = {baseline_results[name]["rmse"]}')

    msg = f'+ mean_rmse = {np.mean(baseline_results[name]["rmse"]):.6f} +/- {np.std(baseline_results[name]["rmse"]):.6f}'
    print(msg)
    print()

    results.append([
        name,
        np.mean(baseline_results[name]["mae"]),
        np.mean(baseline_results[name]["rmse"]),
        np.mean(baseline_results[name]["r2"])
    ])

Model Gradient Boosting:
+ params = {'alpha': 0.9, 'ccp_alpha': 0.0, 'criterion': 'friedman_mse', 'init': None, 'learning_rate': 0.1, 'loss': 'squared_error', 'max_depth': 3, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_iter_no_change': None, 'random_state': 42, 'subsample': 1.0, 'tol': 0.0001, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False}
+ rmse = [np.float64(26825.64985786905), np.float64(23283.475132953834), np.float64(27119.603082380905), np.float64(46906.022254618416), np.float64(23551.351694406425), np.float64(42796.011790129465), np.float64(26925.604114626294), np.float64(23318.833765174157), np.float64(20291.181500140447), np.float64(25471.850271601852)]
+ mean_rmse = 28648.958346 +/- 8397.758726

Model LightGBM:
+ params = {'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': None, 'num_leaves': 31, 'objective': None, 'random_state': 42, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'verbose': -1, 'verbosity': -1}
+ rmse = [np.float64(28760.111826797896), np.float64(32882.03654853373), np.float64(27905.50275620121), np.float64(36631.36406154219), np.float64(24300.93424160724), np.float64(40371.05360103697), np.float64(23956.977351663747), np.float64(21709.749582325352), np.float64(20476.387183252293), np.float64(29291.481848085365)]
+ mean_rmse = 28628.559900 +/- 6130.926219

Model Random Forest:
+ params = {'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}
+ rmse = [np.float64(29485.013282484655), np.float64(27346.339777543013), np.float64(29022.725035853295), np.float64(38953.96456099849), np.float64(27983.5280105224), np.float64(39327.44306110913), np.float64(26618.182858299042), np.float64(23518.52341046107), np.float64(23227.029819896474), np.float64(27904.354865052366)]
+ mean_rmse = 29338.710468 +/- 5280.540371

Model XGBoost:
+ params = {'objective': 'reg:squarederror', 'base_score': None, 'booster': None, 'callbacks': None, 'colsample_bylevel': None, 'colsample_bynode': None, 'colsample_bytree': None, 'device': None, 'early_stopping_rounds': None, 'enable_categorical': False, 'eval_metric': None, 'feature_types': None, 'feature_weights': None, 'gamma': None, 'grow_policy': None, 'importance_type': None, 'interaction_constraints': None, 'learning_rate': None, 'max_bin': None, 'max_cat_threshold': None, 'max_cat_to_onehot': None, 'max_delta_step': None, 'max_depth': None, 'max_leaves': None, 'min_child_weight': None, 'missing': nan, 'monotone_constraints': None, 'multi_strategy': None, 'n_estimators': None, 'n_jobs': None, 'num_parallel_tree': None, 'random_state': 42, 'reg_alpha': None, 'reg_lambda': None, 'sampling_method': None, 'scale_pos_weight': None, 'subsample': None, 'tree_method': None, 'validate_parameters': None, 'verbosity': None}
+ rmse = [np.float64(30692.83590677147), np.float64(32315.361053220495), np.float64(27017.336064090403), np.float64(41757.598398375354), np.float64(27903.489674232504), np.float64(36273.38329960413), np.float64(27214.181009172404), np.float64(27359.650290162703), np.float64(23496.404490900306), np.float64(28489.259169027195)]
+ mean_rmse = 30251.949936 +/- 5053.766466

Model Extra Trees:
+ params = {'bootstrap': False, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}
+ rmse = [np.float64(29520.875026456328), np.float64(29365.621976289465), np.float64(29137.109859285403), np.float64(50460.07225371207), np.float64(26560.95672879103), np.float64(40607.07600931877), np.float64(26199.655160174116), np.float64(26305.982501876933), np.float64(21109.65779783319), np.float64(30792.08288428124)]
+ mean_rmse = 31005.909020 +/- 8012.263405

In [32]:
df_results = pd.DataFrame(
    results,
    columns=["Model", "Mean_RMSE", "Std_RMSE", "RMSE_List"]
)

df_results = df_results.sort_values(by="Std_RMSE", ascending=True)
display.display(df_results)

               Model     Mean_RMSE      Std_RMSE  RMSE_List
1           LightGBM  18321.935447  28628.559900   0.858377
0  Gradient Boosting  17680.118344  28648.958346   0.854380
2      Random Forest  18251.919125  29338.710468   0.850325
3            XGBoost  19206.038965  30251.949936   0.842209
4        Extra Trees  19307.602507  31005.909020   0.830947

**Nhận xét kết quả thực nghiệm các mô hình**

- Kết quả cho thấy Gradient Boosting và LightGBM là hai mô hình hoạt động tốt nhất, với RMSE trung bình lần lượt là 28,648 và 28,628. LightGBM cũng có độ lệch chuẩn thấp, chứng tỏ mô hình ổn định hơn qua các lần thử.

- Random Forest đạt RMSE 29,338, cao hơn một chút so với hai mô hình tốt nhất, cho thấy hiệu quả ở mức khá nhưng chưa tối ưu bằng các mô hình boosting.

- XGBoost (RMSE 30,251) và Extra Trees (RMSE 31,005) cho kết quả kém hơn, đồng thời có độ dao động lớn hơn giữa các fold -> hai mô hình này chưa phù hợp với dữ liệu hiện tại hoặc cần tối ưu thêm siêu tham số.

=> Gradient Boosting và LightGBM là hai mô hình phù hợp nhất để dự đoán giá nhà trong bài toán này.