# Challenge 2: House Prices - Advanced Regression Techniques

## Huấn luyện mô hình cơ bản (Baseline Model Training)

Các mô hình được huấn luyện trên tập dữ liệu gốc (chưa qua feature engineering), nhằm đánh giá hiệu năng cơ bản ban đầu.

### Khai báo thư viện

In [7]:
import pandas as pd
import numpy as np
import random
import os, sys

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

### Tham số thực nghiệm

In [12]:
params = {}

params["exps_dir"] = "../exps"
params["exp_name"] = "challenge2_houseprice_standard"

params["exps_root"] = f'{params["exps_dir"]}/result1_standard'
params["save_dir"] = f'{params["exps_dir"]}/result1_{params["exp_name"]}'

params["data_path"] = f'{params["exps_dir"]}/data/train.xlsx'
params["test_path"] = f'{params["exps_dir"]}/data/test.xlsx'

params["k_fold"] = 10
params["random_state"] = 42

random.seed(params["random_state"])
os.environ['PYTHONHASHSEED'] = str(params["random_state"])
np.random.seed(params["random_state"])

### Nạp dữ liệu

In [13]:
df_train = pd.read_excel(f"{params["data_path"]}")
df_test = pd.read_excel(f"{params["test_path"]}")

In [14]:
df_train.head()

,LotShape,LandContour,LotConfig,Neighborhood,HouseStyle,OverallQual,YearRemodAdd,RoofStyle,Exterior1st,MasVnrArea,...,GrLivArea,FullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,SalePrice
0,0.750731,0.314667,0.604670,-1.206215,1.026689,0.651479,0.878668,-0.491516,0.743092,0.514104,...,0.370333,0.789741,-0.409369,-0.951226,-0.075117,-0.768736,1.005970,0.103495,0.311725,208500
1,0.750731,0.314667,-0.628316,1.954302,-0.543457,-0.071836,-0.429577,-0.491516,-0.508251,-0.570750,...,-0.482512,0.789741,0.795629,0.600495,1.638498,-0.768736,-0.094619,0.103495,0.311725,181500
2,-1.378933,0.314667,0.604670,-1.206215,1.026689,0.651479,0.830215,-0.491516,0.743092,0.325915,...,0.515013,0.789741,-0.409369,0.600495,1.638498,-0.768736,0.924445,0.103495,0.311725,223500
3,-1.378933,0.314667,-1.861302,-1.039872,1.026689,0.651479,-0.720298,-0.491516,1.055928,-0.570750,...,0.383659,-1.026041,-0.409369,0.600495,-0.931925,1.301075,0.802157,0.942959,1.650307,140000
4,-1.378933,0.314667,-0.628316,0.457215,1.026689,1.374795,0.733308,-0.491516,0.743092,1.366489,...,1.299326,0.789741,-0.409369,0.600495,1.638498,-0.768736,0.883682,0.103495,1.650307,250000

In [15]:
df_test.head()

,LotShape,LandContour,LotConfig,Neighborhood,HouseStyle,OverallQual,YearRemodAdd,RoofStyle,Exterior1st,MasVnrArea,...,CentralAir,GrLivArea,FullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars
0,0.750731,0.314667,0.604670,-0.041814,-0.543457,-0.795151,-1.156380,-0.491516,0.743092,-0.570750,...,1,-1.179256,-1.026041,0.795629,-0.951226,-0.075117,-0.768736,-0.706058,0.942959,-1.026858
1,-1.378933,0.314667,-1.861302,-0.041814,-0.543457,-0.071836,-1.301740,1.904521,1.055928,0.027027,...,1,-0.354966,-1.026041,-0.409369,-0.951226,-0.075117,-0.768736,-0.828346,0.942959,-1.026858
2,-1.378933,0.314667,0.604670,-0.707186,1.026689,-0.795151,0.636400,-0.491516,0.743092,-0.570750,...,1,0.216136,0.789741,0.795629,0.600495,1.638498,-0.768736,0.761394,-1.575431,0.311725
3,-1.378933,0.314667,0.604670,-0.707186,1.026689,-0.071836,0.636400,-0.491516,0.743092,-0.460051,...,1,0.168544,0.789741,-0.409369,0.600495,-0.931925,-0.768736,0.802157,-1.575431,0.311725
4,-1.378933,-2.512494,0.604670,1.621616,-0.543457,1.374795,0.345679,-0.491516,-1.133923,-0.570750,...,1,-0.448246,0.789741,-0.409369,-0.951226,-0.075117,-0.768736,0.557582,0.103495,0.311725

In [ ]:
# Tách X, y
y = df_train["SalePrice"]
X = df_train.drop(columns=["SalePrice"])


print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
)

print("Train X:", X_train.shape)
print("Valid X:", X_valid.shape)
print("Train y:", y_train.shape)
print("Valid y:", y_valid.shape)